### ISSUE TITLE
This is code duplication for every shape

### ISSUE THREAD

**Issue by AlexKap23** [Sosa09/TileCost_Calculator#2]
https://github.com/Sosa09/TileCost_Calculator/blob/7821f1668b4cc2438c23299bab780333dc3e1311/TileCost_Calculator/Program.cs#L42

totalCostFlooring value is always being calculated with the same way. The only difference for each one of the shapes is the value of the area. How about calculating it once after calculating the area for each shape?

Actually you are following this approach already with the totalPerHour variable.

**Comment by Sosa09** [comment]
This has been solved now
